

all:
	g++ Principal.cpp -I/home/vlarobbyk/aplicaciones/Librerias/opencv/opencvi/include/opencv4/ -L/home/vlarobbyk/aplicaciones/Librerias/opencv/opencvi/lib/ -lopencv_core -lopencv_highgui -lopencv_video -lopencv_imgproc -lopencv_imgcodecs -lopencv_videoio -o vision.bin
	
run:
	./vision.bin
